window-title: "Tales"                   # Title of the window you want to capture. It can be any part of the window title, for instance "Tales" for "Tales of Phantasia".
refresh-rate: "5s"                      # How often a screenshot is taken
confidence-threshold: 0.9               # Between 0 and 1. Filters out any OCR character with a confidence score below the threshold.
translator:
  api: "google"                         # "google" or "deepl"
  to: "en"                              # Target language. For Google translate, please check here: https://cloud.google.com/translate/docs/languages. For deepL, please check here: https://www.deepl.com/en/docs-api/translating-text
  authentication-key: "deepl-auth-key"  # required only for deepL
