background_color: '#404040'
font_color: '#FFFFFF'
font_size: 42
hotkeys:
  decrease_font: '-'
  increase_font: '='
  quit: q
  switch_mode: m
  toggle_overlay: space
ocr_confidence: 0.6
overlay_mode: banner
refresh_rate: 0.5
window_title: RetroArch Snes9x 1.63 5a40cd5
